spring:
  servlet:
    multipart:
      #设置文件上传大小
      max-file-size: 1000000000
      max-request-size: 1000000000
  profiles:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: update
#      validate 加载hibernate时，验证创建数据库表结构
#      create 每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
#      create-drop 加载hibernate时创建，退出是删除表结构
#      update 加载hibernate自动更新数据库结构
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.240.180:3306/onlineeducation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:mysql://localhost:3306/onlineeducation?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  #配置文件上传路径以及数据库存储路径
  upload:
    imageUrl: D:/ideaIU/GP-upload/img/
    videoUrl: D:/ideaIU/GP-upload/video/
    databaseUrl: http://localhost:8080/files/
    fileMap: /files/**
  # 配置发送方信息
  mail:
    host: smtp.qq.com
    username: 1421894128@qq.com  # 邮箱地址
    password: ebzhjnufqoqwhghe # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  thymeleaf:
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/static/
    suffix: .html
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
#security:
#  basic:
#    enabled: false